feat: epoch3 working with docker-compose

diff --git a/docker-compose-miner.yml b/docker-compose-miner.yml
--- a/docker-compose-miner.yml
+++ b/docker-compose-miner.yml
@@ -1,7 +1,7 @@
 version: "3.9"
 
 x-common-vars:
-  - &STACKS_BLOCKCHAIN_COMMIT feat/naka-neon
+  - &STACKS_BLOCKCHAIN_COMMIT 8cffc3892f6451fdff525952a025f77482a8f728
   - &BTC_ADDR miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT
   - &MINER_SEED 9e446f6b0c6a96cf2190e54bcd5a8569c3e386f091605499464389b8d4e0bfc201 # stx: STEW4ZNT093ZHK4NEQKX8QJGM2Y7WWJ2FQQS5C19, btc: miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT, pub_key: 035379aa40c02890d253cfa577964116eb5295570ae9f7287cbae5f2585f5b2c7c, wif: cStMQXkK5yTFGP3KbNXYQ3sJf2qwQiKrZwR9QJnksp32eKzef1za
   - &BITCOIN_PEER_PORT 18444
@@ -17,7 +17,7 @@ x-common-vars:
   - &STACKS_23_HEIGHT ${STACKS_23_HEIGHT:-106}
   - &STACKS_24_HEIGHT ${STACKS_24_HEIGHT:-107}
   - &STACKS_25_HEIGHT ${STACKS_25_HEIGHT:-108}
-  - &STACKS_30_HEIGHT ${STACKS_30_HEIGHT:-999999} # do not boot into epoch3.0 for now (it doesn't work yet)
+  - &STACKS_30_HEIGHT ${STACKS_30_HEIGHT:-125}
   - &REWARD_RECIPIENT ${REWARD_RECIPIENT:-STQM73RQC4EX0A07KWG1J5ECZJYBZS4SJ4ERC6WN} # priv: 6ad9cadb42d4edbfbe0c5bfb3b8a4125ddced021c4174f829b714ccbf527f02001
 
 services:
@@ -67,7 +67,7 @@ services:
         trap "exit" INT TERM
         trap "kill 0" EXIT
         bitcoin-cli -rpcconnect=bitcoind -rpcwait getmininginfo
-        bitcoin-cli -rpcconnect=bitcoind createwallet ""
+        bitcoin-cli -rpcconnect=bitcoind -named createwallet wallet_name="" descriptors=false
         bitcoin-cli -rpcconnect=bitcoind importaddress $${BTC_ADDR} "" false
         bitcoin-cli -rpcconnect=bitcoind generatetoaddress $${INIT_BLOCKS} $${BTC_ADDR}
         while true; do
@@ -132,8 +132,53 @@ services:
         mkdir -p $${DATA_DIR}
         rm -rf $${DATA_DIR}/*
         envsubst < config.toml.in > config.toml
-        # bitcoin-cli -rpcwait -rpcconnect=bitcoind getmininginfo
+        bitcoin-cli -rpcwait -rpcconnect=bitcoind getmininginfo
         exec stacks-node start --config=config.toml
+
+
+  stacker:
+    networks:
+      - stacks
+    build:
+      context: .
+      dockerfile: Dockerfile.stacker
+    environment:
+      STACKS_CORE_RPC_HOST: stacks-node-miner
+      STACKS_CORE_RPC_PORT: 20443
+    depends_on:
+      - stacks-node-miner
+    entrypoint:
+      - /bin/bash
+      - -c
+      - |
+        SENT_STACKING=0
+        while true; do
+          POX_STATE=$$(curl -s http://stacks-node-miner:20443/v2/pox) || {
+            echo "Curl /v2/pox failed, sleeping for 2 seconds..."
+            sleep 2s
+            continue
+          }
+          INFO_STATE=$$(curl -s http://stacks-node-miner:20443/v2/info) || {
+            echo "Curl /v2/info failed, sleeping for 2 seconds..."
+            sleep 2s
+            continue
+          }
+          STACKS_HEIGHT=$$(echo $${INFO_STATE} | jq -r '.stacks_tip_height')
+          POX_CONTRACT=$$(echo $${POX_STATE} | jq -r '.contract_id')
+          BURN_HEIGHT=$$(echo $${POX_STATE} | jq -r '.current_burnchain_block_height')
+          echo "POX check, stacks=$$STACKS_HEIGHT, burn=$$BURN_HEIGHT, $$POX_CONTRACT"
+          if [ "$$POX_CONTRACT" = "ST000000000000000000002AMW42H.pox-4" ] && [ "$$SENT_STACKING" = "0" ]; then
+            SENT_STACKING=1
+            echo "Stack STX tx for epoch3.0 transition"
+            echo "$$POX_STATE" | jq '.'
+            echo "$$INFO_STATE" | jq '.'
+            MIN_STACKING_AMOUNT="8500000000000000"
+            BURN_HEIGHT=$$(echo $$POX_STATE | jq '.current_burnchain_block_height + 1')
+            node /root/stack.js $$MIN_STACKING_AMOUNT $$BURN_HEIGHT
+            sleep 5s
+          fi
+          sleep 2s
+        done
 
   ##################################
   ##### UNCOMMENT IF USING API #####
